[tool.poetry]
name = "backupsystem"
version = "0.1.0"
description = ""
authors = ["blackflame576 <pws15548@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
schedule = "^1.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
